wandb_version: 1

traindataconfig:
  desc: null
  value:
    num_classes: 512
    dim: 63
    num_labels: 32
    eps: 0.1
    alpha: 0
    ways: 2
    num_seq: 8
    p_bursty: 0.75
    p_icl: 0
    data_type: bursty
icldataconfig:
  desc: null
  value:
    num_classes: 512
    dim: 63
    num_labels: 32
    eps: 0.1
    alpha: 0
    ways: 2
    num_seq: 8
    p_bursty: 0.75
    p_icl: 0
    data_type: holdout
iwldataconfig:
  desc: null
  value:
    num_classes: 512
    dim: 63
    num_labels: 32
    eps: 0.1
    alpha: 0
    ways: 2
    num_seq: 8
    p_bursty: 0.75
    p_icl: 0
    data_type: no_support
icl2dataconfig:
  desc: null
  value:
    num_classes: 512
    dim: 63
    num_labels: 32
    eps: 0.1
    alpha: 0
    ways: 2
    num_seq: 8
    p_bursty: 0.75
    p_icl: 0
    data_type: flip
modelconfig:
  desc: null
  value:
    num_layers: 2
    d_vocab: 32
    d_model: 128
    d_mlp: 128
    d_head: 128
    num_heads: 1
    n_ctx: 17
    act_type: ReLU
    use_cache: false
    use_ln: true
    p_dim: 65
    d_emb: 128
trainconfig:
  desc: null
  value:
    batch_size: 1
    optimize_step: 200000
    lr: 0.01
    optimizer: sgd
device:
  desc: null
  value: cuda:1
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.3
    framework: huggingface
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1711988169.330552
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.13
      5: 0.16.3
      8:
      - 1
      - 5
      13: linux-x86_64
