wandb_version: 1

traindataconfig:
  desc: null
  value:
    num_classes: 512
    dim: 63
    num_labels: 32
    eps: 0.1
    alpha: 0
    ways: 2
    num_seq: 8
    p_bursty: 1
    p_icl: 0
    data_type: bursty
icldataconfig:
  desc: null
  value:
    num_classes: 512
    dim: 63
    num_labels: 32
    eps: 0.1
    alpha: 0
    ways: 2
    num_seq: 8
    p_bursty: 1
    p_icl: 0
    data_type: holdout
iwldataconfig:
  desc: null
  value:
    num_classes: 512
    dim: 63
    num_labels: 32
    eps: 0.1
    alpha: 0
    ways: 2
    num_seq: 8
    p_bursty: 1
    p_icl: 0
    data_type: no_support
icl2dataconfig:
  desc: null
  value:
    num_classes: 512
    dim: 63
    num_labels: 32
    eps: 0.1
    alpha: 0
    ways: 2
    num_seq: 8
    p_bursty: 1
    p_icl: 0
    data_type: flip
modelconfig:
  desc: null
  value:
    num_layers: 2
    num_atten_layer: 2
    d_vocab: 32
    d_model: 128
    d_mlp: 128
    d_head: 128
    num_heads: 1
    n_ctx: 17
    act_type: ReLU
    use_cache: false
    use_ln: true
    p_dim: 65
    d_emb: 128
    seq_model: Attention
    use_scaled_attention: false
trainconfig:
  desc: null
  value:
    batch_size: 1
    optimize_step: 200000
    lr: 0.01
    optimizer: sgd
    every_eval: 3000
device:
  desc: null
  value: cuda:0
exp_name:
  desc: null
  value: some_exp
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711988565.892035
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.16.3
      6: 4.38.2
      8:
      - 5
      13: linux-x86_64
